<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CopperMod.Amiga.Lightweight.Runner</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../../../CopperMod.Amiga.Lightweight/CopperMod.Amiga.Lightweight.csproj" /></ItemGroup>
</Project>
