<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <Copper68kBoundaryVersion Condition="'$(Copper68kBoundaryVersion)' == ''">1.4.2-ocs020.55</Copper68kBoundaryVersion>
  </PropertyGroup>
  <ItemGroup Condition="'$(LightweightReferencePath)' == ''">
    <ProjectReference Include="..\CopperMod.Amiga.Lightweight\CopperMod.Amiga.Lightweight.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(LightweightReferencePath)' != ''">
    <Reference Include="CopperMod.Amiga.Lightweight" HintPath="$(LightweightReferencePath)" Private="true" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Copper68k" Version="[$(Copper68kBoundaryVersion)]" />
  </ItemGroup>
</Project>
